apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector: 
    matchLables:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
